### ISSUE TITLE
 HC-06 BT bridge 

### ISSUE THREAD

**Issue by mkeyno** [winduptoy/grblr#1]
hi , first of apologize for made issue for my question , however I was wondering whether test this application with BT bridge such as HC-06?
thanks

**Comment by winduptoy** [comment]
No but if you'd like to add support I will accept a PR

**Comment by mkeyno** [comment]
I like to help but I'm only c++ programmer and not have any skill for Android , but as you may aware there is many open source BT terminal emulator that can easily ported in your program, however you may interested to  look  this [repo](https://github.com/luc-github/ESP3D) ,  they use wifi connection for sending g-code to the host cnc controller
